/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCommunesRouteImport } from './routes/admin.communes'
import { Route as AdminBannerRouteImport } from './routes/admin.banner'

const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunesRoute = AdminCommunesRouteImport.update({
  id: '/admin/communes',
  path: '/admin/communes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannerRoute = AdminBannerRouteImport.update({
  id: '/admin/banner',
  path: '/admin/banner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/commande': typeof CommandeRoute
  '/panier': typeof PanierRoute
  '/suivi': typeof SuiviRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/communes': typeof AdminCommunesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/commande': typeof CommandeRoute
  '/panier': typeof PanierRoute
  '/suivi': typeof SuiviRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/communes': typeof AdminCommunesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/commande': typeof CommandeRoute
  '/panier': typeof PanierRoute
  '/suivi': typeof SuiviRoute
  '/admin/banner': typeof AdminBannerRoute
  '/admin/communes': typeof AdminCommunesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/commande'
    | '/panier'
    | '/suivi'
    | '/admin/banner'
    | '/admin/communes'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/produit/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/commande'
    | '/panier'
    | '/suivi'
    | '/admin/banner'
    | '/admin/communes'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/produit/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/commande'
    | '/panier'
    | '/suivi'
    | '/admin/banner'
    | '/admin/communes'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/produit/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  CommandeRoute: typeof CommandeRoute
  PanierRoute: typeof PanierRoute
  SuiviRoute: typeof SuiviRoute
  AdminBannerRoute: typeof AdminBannerRoute
  AdminCommunesRoute: typeof AdminCommunesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/communes': {
      id: '/admin/communes'
      path: '/admin/communes'
      fullPath: '/admin/communes'
      preLoaderRoute: typeof AdminCommunesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banner': {
      id: '/admin/banner'
      path: '/admin/banner'
      fullPath: '/admin/banner'
      preLoaderRoute: typeof AdminBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  CommandeRoute: CommandeRoute,
  PanierRoute: PanierRoute,
  SuiviRoute: SuiviRoute,
  AdminBannerRoute: AdminBannerRoute,
  AdminCommunesRoute: AdminCommunesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
